### ISSUE TITLE
Newest Ver. tenshilib-1.18.2-1.6.4 Crashing Server

### ISSUE THREAD

**Issue by Skipperino** [Flemmli97/TenshiLib#5]
### Modloader

Fabric

### Minecraft version

1.18.2

### Modloader version

Fabric 0.13.3 - 1.18.2

### Mod version

1.18.2-1.6.4

### Description

As explained in the title, Tenshilib mod version 1.18.2-1.6.4 is causing server crashes upon server startup. Error log will be posted below.

### Steps to reproduce

1. Step one: Startup server with latest ver. of "tenshilib" and "improved mobs" (dependent on tenshilib)
2. Step two: Crash

### Mods that might affect the issue

Improved mobs relies on Tenshilib as a dependency.

### Logs

---- Minecraft Crash Report ----
// My bad.

Time: 3/19/22, 5:25 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_746
	at io.github.flemmli97.tenshilib.fabric.platform.patreon.PatreonImpl.lambda$sendToClient$1(PatreonImpl.java:44)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.github.flemmli97.tenshilib.fabric.platform.patreon.PatreonImpl.sendToClient(PatreonImpl.java:41)
	at io.github.flemmli97.tenshilib.fabric.platform.patreon.PatreonImpl.onLogin(PatreonImpl.java:30)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents.lambda$static$0(ServerEntityEvents.java:42)
	at net.minecraft.class_3218$class_5526.handler$zji000$invokeEntityLoadEvent(class_3218.java:1635)
	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1519)
	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1480)
	at net.minecraft.class_5579.method_31847(class_5579.java:210)
	at net.minecraft.class_5579.method_31820(class_5579.java:180)
	at net.minecraft.class_5579.method_31818(class_5579.java:161)
	at net.minecraft.class_3218.method_18771(class_3218.java:846)
	at net.minecraft.class_3218.method_18213(class_3218.java:832)
	at net.minecraft.class_3324.method_14570(class_3324.java:233)
	at net.minecraft.class_3248.method_33800(class_3248.java:130)
	at net.minecraft.class_3248.method_14384(class_3248.java:117)
	at net.minecraft.class_3248.redirect$zke000$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18785(class_3248.java:67)
	at net.minecraft.class_2535.method_10754(class_2535.java:243)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918)
	at net.minecraft.class_3176.method_3813(class_3176.java:322)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 26 more

	Fabric Mods: 
		adventurez: AdventureZ 1.4.9
		appleskin: AppleSkin 2.4.0+mc1.18.2
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		architectury: Architectury 4.1.32
		autoconfig1u: Auto Config v1 Updated 3.4.0
		awesomedungeon: Awesome Dungeon 2.0.5
		backslot: BackSlot 1.2.5
		blue_endless_jankson: jankson 1.2.1
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		collective-fabric: Collective (Fabric) 4.20
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		copper_pipe: Simple Copper Pipes r1.9
		disenchanter: Disenchanter 0.1.5+1.18
		dragonloot: DragonLoot 1.0.10
		easymagic: Easy Magic 3.3.0
		enchantinginfuser: Enchanting Infuser 3.2.0
		fabric: Fabric API 0.47.9+1.18.2
		fabric-api-base: Fabric API Base 0.4.3+d7c144a8d2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.6+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.2+801ec85b60
		fabric-command-api-v1: Fabric Command API (v1) 1.1.8+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.7+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.20+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.1+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.10+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.16+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.7+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.18+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.12+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.12+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.2+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.9+3ac43d9560
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.1+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.10+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.3+d1027f7d60
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.20+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.7+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.2+34b2a0ce60
		fabric-particles-v1: Fabric Particles (v1) 0.2.11+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.6+ca4be9c960
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.6+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.1+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.1+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.17+801ec85b60
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.13+d7c144a860
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.13+cca23f9360
		fabricloader: Fabric Loader 0.13.3
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		fiber: fiber 0.23.0-2
		forgeconfigapiport: Forge Config API Port 3.2.0
		friendsandfoes: Friends&Foes 1.2.6
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.8
		guicompass-fabric: GUI Compass (Fabric) 2.2
		healingcampfire-fabric: Healing Campfire (Fabric) 3.3
		improvedmobs: Improved Mobs 1.18.2-1.10.6
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		levelz: LevelZ 1.2.0
		libgui: LibGui 5.3.1+1.18
		libninepatch: LibNinePatch 1.1.0
		libraryferret: Library Ferret 1.0.3
		lithium: Lithium 0.7.9
		medievalweapons: Medieval Weapons 1.1.8
		minecraft: Minecraft 1.18.2
		nameplate: Nameplate 1.0.2
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		pickupnotifier: Pick Up Notifier 3.2.0
		powershot: Powershot 1.4.0-1.18.2-fabric
		puzzleslib: Puzzles Lib 3.3.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reputation: Your Reputation 0.1.1+1.18
		rpgdifficulty: Rpg Difficulty 1.0.11
		sleepwarp: SleepWarp 1.1.1+1.18.2
		tenshilib: TenshiLib 1.18.2-1.6.4
		tradingpost: Trading Post 3.2.0
		villagerfix: Villager Trade Fix 1.0.1
		villagerquests: Villager Quests 1.0.3
		visualworkbench: Visual Workbench 3.2.0
		voicechat: Simple Voice Chat 1.18.2-2.2.26
		wthit: wthit 4.7.2
		xaerominimap: Xaero's Minimap 22.3.0
		xaeroworldmap: Xaero's World Map 1.20.3.1
		yigd: You're in Grave Danger 1.3.1
	Server Running: true
	Player Count: 1 / 50; [class_3222['Skippiest'/88, l='ServerLevel[world]', x=9.50, y=64.00, z=-3.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Flemmli97** [comment]
dont paste logs here
